// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function(emailOptions, sendgridOptions) {
    var SendGrid, errToHTML, objToString, sendgrid;
    SendGrid = require('sendgrid').SendGrid;
    sendgrid = new SendGrid(process.env.SENDGRID_USERNAME || sendGridOptions["username"], process.env.SENDGRID_PASSWORD || sendgridOptions["password"]);
    objToString = function(obj) {
      var p, str;
      str = "";
      for (p in obj) {
        if (obj.hasOwnProperty(p)) {
          str += p + "::" + obj[p] + "\n";
        }
      }
      return str;
    };
    errToHTML = function(err) {
      var stack;
      return stack = (err.stack || '').split('\n').slice(1).map(function(v) {
        return '<li>' + v + '</li>';
      }).join('');
    };
    return {
      emailMe: function(err, req, res, next) {
        sendgrid.send({
          to: emailOptions["to"],
          from: emailOptions["from"],
          subject: emailOptions["subject"],
          html: "<h3>Error:</h3><pre>" + err + "</pre><h3>Stack:</h3><pre>" + (errToHTML(err)) + "</pre><h3>Request:</h3><pre>" + (errToHTML({
            stack: objToString(req)
          })) + "</pre>"
        }, function(success, message) {
          if (!success) {
            return onSendError(message);
          }
        });
        return next(err);
      }
    };
  };

}).call(this);
