// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = function() {
    var SENDGRID_PASSWORD, SENDGRID_USERNAME, SendGrid, errToHTML, objToString, sendgrid;
    SendGrid = require('sendgrid').SendGrid;
    SENDGRID_PASSWORD = "8zihtpty";
    SENDGRID_USERNAME = "app8938131@heroku.com";
    sendgrid = new SendGrid(process.env.SENDGRID_USERNAME || SENDGRID_USERNAME, process.env.SENDGRID_PASSWORD || SENDGRID_PASSWORD);
    objToString = function(obj) {
      var p, str;
      str = "";
      for (p in obj) {
        if (obj.hasOwnProperty(p)) {
          str += p + "::" + obj[p] + "\n";
        }
      }
      return str;
    };
    errToHTML = function(err) {
      var stack;
      return stack = (err.stack || '').split('\n').slice(1).map(function(v) {
        return '<li>' + v + '</li>';
      }).join('');
    };
    return {
      emailMe: function(err, req, res, next) {
        sendgrid.send({
          to: 'exceptions@messagesonamission.com',
          from: 'exception.notifier@MessagesOnAMission.com',
          subject: 'Omphalos Responder Error',
          html: "<h3>Error:</h3><pre>" + err + "</pre><h3>Request:</h3><pre>" + (errToHTML({
            stack: objToString(req)
          })) + "</pre><h3>Stack:</h3><pre>" + (errToHTML(err)) + "</pre>"
        }, function(success, message) {
          if (!success) {
            return console.log("OmphalosError-304", message);
          }
        });
        return next(err);
      }
    };
  };

}).call(this);
